version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  webapp:
    image: selection-process-administration
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__AplicationDbConection: "Server=sqlserver;Database=SelecctionProcess;User Id=sa;Password=Passw0rd!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - mynetwork

networks:
  mynetwork: